# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('v2v-clustering-example', ['v2v'])
    obj.source = 'v2v-clustering-example.cc'
